### ISSUE TITLE
Mod settings menu does not show proper text

### ISSUE THREAD

**Issue by EternalWait** [Yuoki-Industries/yuoki#13]
The text for changing the mod settings found in ( Mod settings menu then Startup ) does not show proper text.

The option to enable productivity modules , extra inventory and extra reach need proper text.

This seems to be a simple fix in the settings.lua by adding localised_name  = "Enable Productivity for some machines"  etc.

**Comment by ChurchOrganist** [comment]
Already fixed in next version  - the settings.cfg file got omitted from the upload in error
